using Microsoft.EntityFrameworkCore;

namespace mvc
{
    public class FilmContext : DbContext
    {
        public DbSet<Film> Films { get; set; }
        public FilmContext(DbContextOptions<FilmContext> options)
           : base(options)
        {
            if (Database.EnsureCreated())
            {
                Films?.Add(new Film { Name = "Бесславные ублюдки", Director = "Квентин Тарантино", Genre = "Военный фильм, Боевик, Кинокомедия, Чёрный юмор, Приключения, Триллер, Драма, Саспенс, Криминальный жанр", Year = 2009, Description = "Вторая мировая война, в оккупированной немцами Франции группа американских солдат-евреев наводит страх на нацистов, жестоко убивая и скальпируя солдат.", Poster = "https://upload.wikimedia.org/wikipedia/ru/thumb/c/c3/Inglourious_Basterds_poster.jpg/250px-Inglourious_Basterds_poster.jpg", TrailerLink = "https://www.youtube.com/embed/pZEZ1yDIHEU?si=5PjF9ywteMPEtGsG" });
                Films?.Add(new Film { Name = "Старикам тут не место", Director = "Итан Коэн, Джоэл Коэн", Genre = "Нео-вестерн, криминальный триллер, драма", Year = 2007, Description = "Обычный работяга обнаруживает в пустыне гору трупов, грузовик, набитый героином, и соблазнительную сумму в два миллиона долларов наличными. Он решает взять деньги себе, и результатом становится волна насилия, которую не может остановить вся полиция Западного Техаса.", Poster = "https://lh4.googleusercontent.com/proxy/T_kKcsVDX8JHoel8Zr52OnuKYl4ACCaQmsy0l5sy0qpxttDPc5CJ18IGCXt9yz1gqAzY7UwuiGyud4A_5MjQ2vn7K5s2qof0cJRsZVMbEP1wTC5XVuGQae1Pg0Y", TrailerLink = "https://www.youtube.com/embed/9DgsztNQmRU?si=_gVhE8WbwxF6aWwL" });
                Films?.Add(new Film { Name = "Пираты Карибского моря: Проклятие Чёрной жемчужины", Director = "Гор Вербински", Genre = "Приключения, Боевик", Year = 2003, Description = "Жизнь харизматичного авантюриста, капитана Джека Воробья, полная увлекательных приключений, резко меняется, когда его заклятый враг — капитан Барбосса — похищает корабль Джека, Черную Жемчужину, а затем нападает на Порт Ройал и крадет прекрасную дочь губернатора, Элизабет Свонн.", Poster = "https://static.hdrezka.ac/i/2013/8/14/c7f84934738c2fw18s42a.jpg", TrailerLink = "https://www.youtube.com/embed/SBxju8HuSIQ?si=R1ThqgaVs_uBW3F5" });
                Films?.Add(new Film { Name = "Пираты Карибского моря: Сундук мертвеца", Director = "Гор Вербински", Genre = "Приключения, Боевик", Year = 2006, Description = "Вновь оказавшись в ирреальном мире, лихой капитан Джек Воробей неожиданно узнает, что является должником легендарного капитана «Летучего Голландца» Дэйви Джонса. Джек должен в кратчайшие сроки решить эту проблему, иначе ему грозит вечное проклятие и рабское существование после смерти. Вдобавок ко всему, срывается свадьба Уилла Тернера и Элизабет Суонн, которые вынуждены составить Джеку компанию в его злоключениях…", Poster = "https://static.hdrezka.ac/i/2021/6/12/kefd7a83cd8cczr32i60d.jpeg", TrailerLink = "https://www.youtube.com/embed/TV0j8S7JUpA?si=8-RaZRF-6_ZrnYD1" });
                Films?.Add(new Film { Name = "Пираты Карибского моря: На краю света", Director = "Гор Вербински", Genre = "Приключения, Боевик", Year = 2007, Description = "Новые приключения Джека Воробья и его друзей Уилла Тернера и Элизабет Суонн. На этот раз Уиллу и Элизабет придется объединиться с самим Капитаном Барбоссой для того, чтобы отправиться на край света и спасти своего друга — Джека. Ситуация осложняется тем, что Элизабет попадает к сингапурским пиратам…", Poster = "https://upload.wikimedia.org/wikipedia/ru/e/ee/Pirates3.jpg", TrailerLink = "https://www.youtube.com/embed/TV0j8S7JUpA?si=k_2bW6SC5m25P4I-" });
                Films?.Add(new Film { Name = "Пираты Карибского моря: На странных берегах", Director = "Гор Вербински", Genre = "Приключения, Боевик", Year = 2011, Description = "В новой истории о поисках истины, предательстве, вечной молодости и смертельной опасности капитану Джеку Воробью предстоит столкнуться с женщиной из своего прошлого Анжеликой. До самого конца не будет понятно, связывает ли их настоящая любовь, или же Анжелика искусно притворяется, чтобы вместе с Джеком добраться до таинственного источника вечной молодости.", Poster = "https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/1e66be7b-2b59-446c-b603-fa10f48570fd/orig", TrailerLink = "https://www.youtube.com/embed/xICp7J0kEmY?si=n_2J66rBI8FLlQch" });
                Films?.Add(new Film { Name = "Пираты Карибского моря: Мертвецы не рассказывают сказки", Director = "Гор Вербински", Genre = "Приключения, Боевик", Year = 2017, Description = "Исчерпавший свою удачу капитан Джек Воробей обнаруживает, что за ним охотится его старый неприятель, ужасный капитан Салазар и его призрачные пираты. Они только что сбежали из Дьявольского треугольника и намерены уничтожить всех пиратов, включая Джека. Поможет спастись лишь могущественный артефакт — трезубец Посейдона, который дарует своему обладателю полный контроль над морями.", Poster = "https://s.afisha.ru/mediastorage/73/7e/a4c86857319748019d0122ba7e73.jpeg", TrailerLink = "https://www.youtube.com/embed/GQR23Ri73pE?si=NFYkyyu8XIa1hL0a" });
                Films?.Add(new Film { Name = "Терминатор 2: Судный день", Director = "Джеймс Кэмерон", Genre = "Боевик, Научная фантастика", Year = 1991, Description = "Прошло более десяти лет с тех пор, как киборг-терминатор из 2029 года пытался уничтожить Сару Коннор — женщину, чей будущий сын выиграет войну человечества против машин.", Poster = "https://static.hdrezka.ac/i/2021/10/17/n76429e9a6f4ffq70o61b.jpeg", TrailerLink = "https://www.youtube.com/embed/V2wMFn-z6ik?si=l7HELsvx-4R1WR3h" });
                Films?.Add(new Film { Name = "Чужой: Завет", Director = "Ридли Скотт", Genre = "Научная фантастика, Ужасы", Year = 2017, Description = "Во время обследования удаленной планеты, расположенной на другой стороне галактики, экипаж колониального корабля «Завет» обнаруживает, что то, что они изначально приняли за неизведанный рай, на самом деле — тёмный и опасный мир. Его единственный житель — синтетический андроид Дэвид, оставшийся в живых после обреченной экспедиционной миссии «Прометей».", Poster = "https://static.hdrezka.ac/i/2021/8/18/ga6bd0edcfc58jb46t48y.png", TrailerLink = "https://www.youtube.com/embed/wIfpSQ9qGvU?si=X5524Ni-dqzy4ZrG" });
                Films?.Add(new Film { Name = "Чужие против Хищника: Реквием", Director = "Грег Страузе, Колин Штраус", Genre = "Ужасы, Научная фантастика", Year = 2007, Description = "«Чужие против Хищника: Реквием» — научно-фантастический боевик ужасов Колина и Грега Штраусов, являющийся продолжением фильма «Чужой против Хищника» 2004 года. Фильм объединяет два фантастических цикла: «Чужой» и «Хищник», и персонажей из них. Это единственный фильм про Чужого и Хищника, который не имеет новеллизации.", Poster = "https://static.hdrezka.ac/i/2014/4/18/de0594cd0a414tz97p43w.jpg", TrailerLink = "https://www.youtube.com/embed/cQHDh9nfDM4?si=_OZPWa2uOH8-DKsf" });



                SaveChanges();
            }
        }
    }
}